### ISSUE TITLE
Error in file(file, "rt") : cannot open the connection

### ISSUE THREAD

**Issue by MustafaElshani** [gexijin/idepGolem#439] opened 2022-12-05 18:43 UTC
**Describe the bug**
Upon 'idepGolem::run_app()' the browser opens and closes with error 

**To Reproduce**
idepGolem::run_app() 

**Expected behavior**
All dependencies were installed via `devtools::install ` with success 
I am expected for the the shiny app to open and use idep

**Additional context**
```
 runApp('idepGolem')
Warning in loadSupport(appDir, renv = sharedEnv, globalrenv = NULL) :
  Loading R/ subdirectory for Shiny application, but this directory appears to contain an R package. Sourcing files in R/ may cause unexpected behavior.

Listening on http://127.0.0.1:4075
Warning: Error in file: cannot open the connection
  51: file
  50: read.table
  49: read.csv
  48: get_idep_data
  47: server
   1: runApp
Error in file(file, "rt") : cannot open the connection

```

**Comment by MustafaElshani** [comment] 2022-12-08 14:15
Dear @espors 

Thank you for you reply I have added the database via `export IDEP_DATABASE='/home/mustafa/projects/bioinformatic_tools/idepGolem/data'
`
However that did not help

**Comment by espors** [comment] 2022-12-12 21:46
To confirm, did you set up the environmental variable name?

**Comment by MustafaElshani** [comment] 2022-12-12 22:37
Hi @espors apart from the 'export' above I have not set anything else. I do run this conda environment with all dependencies installed 

Any suggestions on how to setup the environmental variable in linux aparr from the export?

**Comment by Luiky1** [comment] 2023-01-25 11:12
Hello, same problem for me:
> idepGolem::run_app() 

Listening on http://127.0.0.1:3489
Warning in file(con, "r") :
  cannot open file 'inst/app/www/help_preprocess.htm': No such file or directory
Warning: Error in file: cannot open the connection
  108: file
  107: readLines
  106: includeHTML
   84: mod_02_pre_process_ui
   69: ui
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>


Any suggestion? Thanks in advance

**Comment by gexijin** [comment] 2023-01-25 14:07
Like what [MustafaElshani](https://github.com/MustafaElshani) is asking, please check
1. Download the big 200GB database to a folder:
2. Set up an environmental variable IDEB_DATABASE to point to that folder.

**Comment by semenko** [comment] 2023-02-21 16:54
I also have this error, not entirely sure where idep is looking for data -- it'd be helpful if more debug info were printed during load.

e.g. 
```
> devtools::install_github("https://github.com/espors/idepGolem", force=TRUE)
…
(Succeeds)
…
> Sys.setenv(IDEP_DATABASE="/home/user/idep_data")
> Sys.getenv("IDEP_DATABASE")
[1] "/home/user/idep_data"
> list.files(Sys.getenv("IDEP_DATABASE"))
 [1] "convertIDs.db"        "convertIDs.db.tar.gz" "data_go"             
 [4] "data_go.tar.gz"       "geneInfo"             "geneInfo.tar.gz"     
 [7] "motif"                "motif.tar.gz"         "pathwayDB"           
[10] "pathwayDB.tar.gz"   
> idepGolem::run_app()

Listening on http://127.0.0.1:5730
Warning: Error in file: cannot open the connection
  44: file
  43: read.table
  42: read.csv
  41: get_idep_data
  40: server
   3: runApp
   2: print.shiny.appobj
   1: <Anonymous>
Error in file(file, "rt") : cannot open the connection
```

**Comment by usergrin** [comment] 2023-02-22 21:31
Dear all,

I can add onto this issue that I run into similar issues on multiple linux machines. Also it seems therefore reproducible, in the sense of me doing something wrong here..

The system variable is there, 
~~~
> list.files(Sys.getenv("IDEP_DATABASE"))
[1] "convertIDs.db" "data_go"       "dl.txt"        "geneInfo"     
[5] "motif"         "pathwayDB"    
~~~
and idepGolem has been built with the git/devtools::install, the direct devtools::install_github and the remotes::install_github method. I feel like there is even something wrong on my machines with the 2nd and 3rd method, because only git/devtools is able to show me a (still broken) website. (was not able to get the same results by changing working directory to the library/package)

The error in the run_app() output is always the same:
~~~
cannot open file 'inst/app/www/help_preprocess.htm': No such file or directory
Warning: Error in file: cannot open the connection
  99: file
  98: readLines
  97: includeHTML
  75: mod_02_pre_process_ui
  60: ui
   3: runApp
   2: print.shiny.appobj
   1: <Anonymous>
~~~

And the build process threw the following warnings:
~~~
Note: possible error in 'deg_limma(processed_data = processed_data, ': unused argument (descr = descr) 
Note: possible error in 'deg_limma(processed_data = processed_data, ': unused argument (descr = descr) 
Note: possible error in 'get_gene_info(load_data$converted(), ': unused argument (all_gene_info = idep_data$gene_info_files) 
~~~

Website displays:
~~~
An error has occurred!
cannot open the connection
~~~

**Comment by MustafaElshani** [comment] 2023-03-15 13:50
The way I overcame this issue is not using rstudio and starting via Rscript
'Rscript app.R'

**Comment by gexijin** [comment] 2023-03-15 16:13
Dear all, I will look into this issue.

**Comment by gexijin** [comment] 2023-03-15 17:17
If you get this error (read.csv) that means your database path is not being set correctly.  The pre-process.html is another issue. It comes with the R package. I am working on this right now.

```
Listening on http://127.0.0.1:3119
Warning: Error in file: cannot open the connection
  53: file
  52: read.table
  51: read.csv
  50: get_idep_data [C:/work/idepGolem/R/fct_database.R#73]
  49: server [C:/work/idepGolem/R/app_server.R#15]
   3: runApp
   2: print.shiny.appobj
   1: <Anonymous>
Error in file(file, "rt") : cannot open the connection
```

**Comment by gexijin** [comment] 2023-03-15 18:17
Hi guys, this problem is solved.  I used the system.files to find the html files needed for the app. For some reason, I had to rename help_preprocess.htm to help_preprocess.html. 

Note that the installation URL is also changed: `devtools::install_github("https://github.com/gexijin/idepGolem")`
It was pointing to my student Emma's repo. She graduated. 

We are also working on a new version where the database is separated by species. That will be much easier to run iDEP from local machines as the database will be much smaller. 
That version will be release early April. 

Thank you for your feedback. Please don't hesitate to send us emails: gelabinfo@gmail.com.

**Comment by gexijin** [comment] 2023-04-29 19:19
This is fixed in the new version, as the database files are automatically downloaded.

**Closed by gexijin** 2023-04-29 19:19 UTC
Labels: help wanted, database
